"use strict";

/**
 * DashboardRenderer — renders metrics snapshots as plain-text dashboards
 * with ANSI colors, ASCII bar charts, and sparklines.
 */

// Re-use the same ANSI / THEME constants as the main renderer
const ANSI = {
  reset: "\x1B[0m",
  bold: "\x1B[1m",
  dim: "\x1B[2m",
  red: "\x1B[31m",
  green: "\x1B[32m",
  yellow: "\x1B[33m",
  blue: "\x1B[34m",
  magenta: "\x1B[35m",
  cyan: "\x1B[36m",
  white: "\x1B[37m",
  brightRed: "\x1B[91m",
  brightGreen: "\x1B[92m",
  brightYellow: "\x1B[93m",
  brightBlue: "\x1B[94m",
  brightMagenta: "\x1B[95m",
  brightCyan: "\x1B[96m",
  brightWhite: "\x1B[97m",
  bgBrightBlack: "\x1B[100m",
};

const THEME = {
  heading: ANSI.bold + ANSI.brightCyan,
  subheading: ANSI.bold + ANSI.brightWhite,
  success: ANSI.brightGreen,
  warning: ANSI.brightYellow,
  error: ANSI.brightRed,
  muted: ANSI.dim,
  accent: ANSI.brightMagenta,
  cost: ANSI.brightYellow,
  token: ANSI.dim,
  border: ANSI.dim,
  info: ANSI.brightBlue,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const BAR_CHARS = ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"];
const SPARK = ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"];

function padRight(str, len) {
  return str.length >= len ? str : str + " ".repeat(len - str.length);
}

function padLeft(str, len) {
  const s = String(str);
  return s.length >= len ? s : " ".repeat(len - s.length) + s;
}

function barChart(value, max, width) {
  width = width || 20;
  if (max === 0) return ANSI.dim + "─".repeat(width) + ANSI.reset;
  const ratio = Math.min(1, Math.max(0, value / max));
  const filled = Math.round(ratio * width);
  const empty = width - filled;
  return (
    ANSI.brightCyan +
    "█".repeat(filled) +
    ANSI.dim +
    "─".repeat(empty) +
    ANSI.reset
  );
}

function barChartLabeled(label, value, max, width) {
  const chart = barChart(value, max, width || 20);
  return `${padRight(label, 18)} ${chart} ${ANSI.brightWhite}${value}${ANSI.reset}`;
}

function sparkline(values, width) {
  width = width || 12;
  if (!Array.isArray(values) || values.length === 0) {
    return ANSI.dim + "─".repeat(width) + ANSI.reset;
  }
  const max = Math.max(...values, 1);
  const min = Math.min(...values, 0);
  const range = max - min || 1;

  let result = "";
  for (let i = 0; i < Math.min(values.length, width); i++) {
    const ratio = (values[i] - min) / range;
    const idx = Math.min(SPARK.length - 1, Math.max(0, Math.floor(ratio * SPARK.length)));
    result += SPARK[idx];
  }
  return ANSI.brightGreen + result + ANSI.reset;
}

function healthIcon(status) {
  if (status === "pass") return ANSI.brightGreen + "✓" + ANSI.reset;
  if (status === "warn") return ANSI.brightYellow + "⚠" + ANSI.reset;
  return ANSI.brightRed + "✗" + ANSI.reset;
}

function divider(width) {
  width = width || 60;
  return ANSI.dim + "─".repeat(width) + ANSI.reset;
}

function sectionHeader(title) {
  return THEME.heading + "\n┌─ " + title + " " + "─".repeat(50) + ANSI.reset;
}

function formatMs(ms) {
  if (ms < 1000) return `${Math.round(ms)}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60000).toFixed(1)}m`;
}

function formatNumber(n) {
  if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}K`;
  return String(Math.round(n));
}

function formatCost(n) {
  return `$${n.toFixed(4)}`;
}

// ---------------------------------------------------------------------------
// DashboardRenderer
// ---------------------------------------------------------------------------

class DashboardRenderer {
  constructor() {
    this._termWidth = 80;
  }

  /**
   * Render a full dashboard overview from a snapshot.
   *
   * @param {object} snapshot — result of MetricsCollector.getSnapshot()
   * @returns {string} plain-text ANSI-colored dashboard
   */
  renderOverview(snapshot) {
    const lines = [];

    // Header
    lines.push("");
    lines.push(THEME.heading + ANSI.bold + "  HAXAGENT METRICS DASHBOARD" + ANSI.reset);
    lines.push(
      ANSI.muted +
        "  " +
        new Date(snapshot.timestamp).toLocaleString() +
        ANSI.reset
    );
    lines.push("");

    // Health summary
    lines.push(this._renderHealthBar(snapshot.health));
    lines.push(divider(70));

    // Sections
    lines.push(this.renderToolSection(snapshot.tools));
    lines.push(this.renderSessionSection(snapshot.sessions));
    lines.push(this.renderTokenSection(snapshot.tokens));
    lines.push(this.renderHealthSection(snapshot.health, snapshot.system));
    lines.push(this._renderAgentSection(snapshot.agent));

    // Footer
    lines.push(divider(70));
    lines.push(
      ANSI.muted +
        "  Generated by HaxAgent Dashboard v1.0" +
        ANSI.reset
    );
    lines.push("");

    return lines.join("\n");
  }

  /**
   * Render tool usage section with ASCII bar charts.
   */
  renderToolSection(metrics) {
    if (!metrics) return "";

    const lines = [];
    lines.push(sectionHeader("TOOL USAGE"));

    lines.push(
      `  ${ANSI.brightWhite}Executions:${ANSI.reset} ${metrics.totalExecutions}  ` +
        `${ANSI.green}Success:${ANSI.reset} ${metrics.successCount} (${metrics.successRate}%)  ` +
        `${ANSI.red}Errors:${ANSI.reset} ${metrics.totalErrors} (${metrics.errorRate}%)`
    );
    lines.push(
      `  ${ANSI.brightWhite}Duration:${ANSI.reset} avg ${formatMs(metrics.avgDurationMs)}  ` +
        `min ${formatMs(metrics.minDurationMs)}  max ${formatMs(metrics.maxDurationMs)}`
    );

    if (metrics.topTools && metrics.topTools.length > 0) {
      lines.push(`  ${ANSI.brightWhite}Top Tools:${ANSI.reset}`);
      const maxCount = metrics.topTools[0].count;
      for (const tool of metrics.topTools) {
        const fullLabel = `    ${tool.name}`;
        lines.push(barChartLabeled(fullLabel, tool.count, maxCount, 25));
      }
    }

    return lines.join("\n");
  }

  /**
   * Render session stats with sparklines.
   */
  renderSessionSection(metrics) {
    if (!metrics) return "";

    const lines = [];
    lines.push(sectionHeader("SESSION STATS"));

    const sparkVals = Array.isArray(metrics.turnsHistory)
      ? metrics.turnsHistory
      : [];

    lines.push(
      `  ${ANSI.brightWhite}Sessions:${ANSI.reset} ${metrics.totalSessions}  ` +
        `(${metrics.sessionsPerDay}/day)`
    );
    lines.push(
      `  ${ANSI.brightWhite}Turns:${ANSI.reset} avg ${metrics.avgTurnsPerSession}/session  ` +
        `max ${metrics.maxTurns}`
    );

    if (sparkVals.length > 0) {
      lines.push(`  ${ANSI.brightWhite}Activity:${ANSI.reset} ${sparkline(sparkVals, 30)}`);
    }

    lines.push(
      `  ${ANSI.brightWhite}Cost:${ANSI.reset} ${formatCost(metrics.totalCost)} total  ` +
        `${formatCost(metrics.avgCostPerSession)} avg/session`
    );
    lines.push(
      `  ${ANSI.brightWhite}Tokens:${ANSI.reset} ${formatNumber(metrics.totalTokens)} total  ` +
        `${formatNumber(metrics.avgTokensPerSession)} avg/session`
    );

    return lines.join("\n");
  }

  /**
   * Render system health indicators.
   */
  renderHealthSection(health, system) {
    if (!health || !system) return "";

    const lines = [];
    lines.push(sectionHeader("SYSTEM HEALTH"));

    for (const check of health.checks) {
      lines.push(
        `  ${healthIcon(check.status)} ${ANSI.brightWhite}${padRight(check.label, 22)}${ANSI.reset} ${check.value}`
      );
    }

    // Memory bar
    const memPercent = system.memory ? system.memory.usagePercent : 0;
    lines.push(
      `  ${ANSI.brightWhite}Memory:${ANSI.reset} ${barChart(memPercent, 100, 20)} ${memPercent}%`
    );

    // CPU bar
    const cpuPercent = system.cpu ? system.cpu.usagePercent : 0;
    lines.push(
      `  ${ANSI.brightWhite}CPU:   ${ANSI.reset} ${barChart(cpuPercent, 100, 20)} ${cpuPercent}%`
    );

    // Load averages
    if (system.cpu && (system.cpu.loadAvg1m || system.cpu.loadAvg5m)) {
      lines.push(
        `  ${ANSI.brightWhite}Load:  ${ANSI.reset} ${system.cpu.loadAvg1m} / ${system.cpu.loadAvg5m} / ${system.cpu.loadAvg15m}`
      );
    }

    // Uptime
    lines.push(
      `  ${ANSI.brightWhite}Uptime:${ANSI.reset} ${system.uptimeHours} hours`
    );

    return lines.join("\n");
  }

  /**
   * Render token usage and cost charts.
   */
  renderTokenSection(metrics) {
    if (!metrics) return "";

    const lines = [];
    lines.push(sectionHeader("TOKEN USAGE & COST"));

    const total = metrics.totalTokens || 1;
    const inputPct = ((metrics.totalInput || 0) / total) * 100;
    const outputPct = ((metrics.totalOutput || 0) / total) * 100;
    const cachePct = ((metrics.totalCacheCreation || 0) / total) * 100;

    lines.push(
      `  ${THEME.info}Input:${ANSI.reset}  ${formatNumber(metrics.totalInput || 0)} tokens (${inputPct.toFixed(1)}%)`
    );
    lines.push(
      `  ${ANSI.magenta}Output:${ANSI.reset} ${formatNumber(metrics.totalOutput || 0)} tokens (${outputPct.toFixed(1)}%)`
    );
    lines.push(
      `  ${THEME.muted}Cache:${ANSI.reset}  ${formatNumber(metrics.totalCacheCreation || 0)} tokens (${cachePct.toFixed(1)}%)`
    );
    lines.push(
      `  ${ANSI.brightWhite}Total:${ANSI.reset} ${formatNumber(metrics.totalTokens)} tokens  ` +
        `avg ${formatNumber(metrics.avgTokensPerTurn)}/turn`
    );

    // Token composition bar
    const inputBar = Math.round((inputPct / 100) * 40);
    const outputBar = Math.round((outputPct / 100) * 40);
    const cacheBar = Math.round((cachePct / 100) * 40);
    lines.push(
      `  ${ANSI.brightBlue}${"█".repeat(inputBar)}${ANSI.magenta}${"█".repeat(outputBar)}${ANSI.dim}${"█".repeat(cacheBar)}${ANSI.reset}`
    );

    // Cost
    const cost = metrics.costEstimate || {};
    lines.push(
      `  ${ANSI.brightWhite}Est. Cost:${ANSI.reset} ${formatCost(cost.total || 0)}`
    );

    if (cost.breakdown && Object.keys(cost.breakdown).length > 0) {
      lines.push(`  ${ANSI.brightWhite}Breakdown:${ANSI.reset}`);
      for (const [provider, amt] of Object.entries(cost.breakdown)) {
        lines.push(`    ${provider}: ${formatCost(amt)}`);
      }
    }

    return lines.join("\n");
  }

  // -----------------------------------------------------------------------
  // Internal
  // -----------------------------------------------------------------------

  _renderHealthBar(health) {
    const status = health.overall || "warn";
    const label =
      status === "pass" ? "HEALTHY" : status === "fail" ? "UNHEALTHY" : "DEGRADED";
    const color =
      status === "pass"
        ? ANSI.brightGreen
        : status === "fail"
          ? ANSI.brightRed
          : ANSI.brightYellow;
    const bgColor =
      status === "pass"
        ? ANSI.bgBrightBlack
        : status === "fail"
          ? ANSI.bgBrightBlack
          : ANSI.bgBrightBlack;

    return (
      `  ${bgColor}${color}${ANSI.bold} ${label} ${ANSI.reset}` +
      `  ${ANSI.muted}${health.checks.filter((c) => c.status === "pass").length}/${health.checks.length} checks passing${ANSI.reset}`
    );
  }

  _renderAgentSection(agent) {
    if (!agent) return "";

    const lines = [];
    lines.push(sectionHeader("AGENT PERFORMANCE"));

    lines.push(
      `  ${ANSI.brightWhite}Turns:${ANSI.reset}     ${agent.totalTurns}`
    );
    lines.push(
      `  ${ANSI.brightWhite}Avg Response:${ANSI.reset} ${formatMs(agent.avgResponseTimeMs)}`
    );
    lines.push(
      `  ${ANSI.brightWhite}Error Rate:${ANSI.reset}  ${(agent.errorRate * 100).toFixed(2)}%`
    );

    return lines.join("\n");
  }
}

module.exports = { DashboardRenderer, THEME, ANSI, barChart, sparkline, healthIcon };
