"use strict";

const fs = require("node:fs");
const path = require("node:path");

const { PLUGIN_HOOK_NAMES } = require("../plugins");

/**
 * Dev Tooling: Scaffold
 *
 * Generates skeleton files for plugins, skills, tools, agents, and tests.
 * Each function writes complete, working code to the target directory.
 */

// ── Plugin Scaffold ──────────────────────────────────────────────────────────

/**
 * Generates a plugin skeleton with all 7 hooks as commented stubs,
 * a package.json, and a README.
 *
 * @param {string} name - Plugin name (kebab-case, e.g. "my-logger")
 * @param {string} outputDir - Directory to write files into
 * @returns {{ files: string[] }} Paths of created files
 */
function scaffoldPlugin(name, outputDir) {
  const sanitized = sanitizeName(name);
  const dir = path.resolve(outputDir, sanitized);
  const files = [];

  fs.mkdirSync(dir, { recursive: true });

  // package.json
  const pkgPath = path.join(dir, "package.json");
  fs.writeFileSync(pkgPath, JSON.stringify({
    name: `hax-agent-plugin-${sanitized}`,
    version: "1.0.0",
    description: `Hax Agent plugin: ${sanitized}`,
    main: "index.js",
    keywords: ["hax-agent", "plugin"],
    license: "MIT",
  }, null, 2) + "\n", "utf-8");
  files.push(pkgPath);

  // README.md
  const readmePath = path.join(dir, "README.md");
  fs.writeFileSync(readmePath, [
    `# ${sanitized}`,
    "",
    `A Hax Agent plugin generated by the dev-tooling scaffolder.`,
    "",
    "## Installation",
    "",
    "Copy this directory into `.hax-agent/plugins/` or register programmatically:",
    "",
    "```js",
    `const ${toCamelCase(sanitized)} = require('./${sanitized}/index.js');`,
    `registry.register(${toCamelCase(sanitized)});`,
    "```",
    "",
    "## Hooks",
    "",
    ...PLUGIN_HOOK_NAMES.map((h) => `- \`${h}\``),
    "",
  ].join("\n") + "\n", "utf-8");
  files.push(readmePath);

  // index.js — main plugin module
  const hooksStubs = PLUGIN_HOOK_NAMES.map((hookName) => {
    return [
      `/**`,
      ` * ${hookName} hook.`,
      ` * @param {object} ctx - Hook context object`,
      ` * @returns {object} ctx (pass-through or mutated)`,
      ` */`,
      `function ${hookName}(ctx) {`,
      `  // TODO: implement ${hookName} logic`,
      `  return ctx;`,
      `}`,
    ].join("\n");
  }).join("\n\n");

  const moduleCode = [
    `"use strict";`,
    ``,
    `/**`,
    ` * ${sanitized} — a Hax Agent plugin.`,
    ` *`,
    ` * Generated by the dev-tooling scaffolder.`,
    ` * Fill in the hook bodies below to add custom behaviour.`,
    ` */`,
    ``,
    `// ── Hook implementations ───────────────────────────────────────────`,
    ``,
    hooksStubs,
    ``,
    `// ── Plugin descriptor ───────────────────────────────────────────────`,
    ``,
    `const plugin = {`,
    `  name: "${sanitized}",`,
    `  version: "1.0.0",`,
    `  description: "TODO: describe what this plugin does",`,
    `  hooks: {`,
    ...PLUGIN_HOOK_NAMES.map((h) => `    ${h},`),
    `  },`,
    `};`,
    ``,
    `module.exports = plugin;`,
    `module.exports.register = function register(registry) {`,
    `  registry.register(plugin);`,
    `};`,
    ``,
  ].join("\n") + "\n";

  const indexPath = path.join(dir, "index.js");
  fs.writeFileSync(indexPath, moduleCode, "utf-8");
  files.push(indexPath);

  return { files, dir };
}

// ── Skill Scaffold ───────────────────────────────────────────────────────────

/**
 * Generates a skill skeleton with frontmatter template, argument parsing,
 * and an execute function.
 *
 * @param {string} name - Skill name (e.g. "code-review")
 * @param {string} outputDir - Directory to write files into
 * @returns {{ files: string[], dir: string }}
 */
function scaffoldSkill(name, outputDir) {
  const sanitized = sanitizeName(name);
  const dir = path.resolve(outputDir, sanitized);
  const files = [];

  fs.mkdirSync(dir, { recursive: true });

  const skillMd = [
    `---`,
    `name: ${sanitized}`,
    `description: A skill that helps with ${sanitized.replace(/-/g, " ")}`,
    `arguments:`,
    `  - input`,
    `user-invocable: true`,
    `---`,
    ``,
    `# ${sanitized}`,
    ``,
    `## Overview`,
    ``,
    `TODO: Describe what this skill does and when it should be used.`,
    ``,
    `## Instructions`,
    ``,
    `When invoked with arguments:`,
    ``,
    `- \`$input\`: The input passed by the user.`,
    ``,
    `## Output`,
    ``,
    `TODO: Specify the expected output format or conventions.`,
    ``,
  ].join("\n") + "\n";

  const skillPath = path.join(dir, "SKILL.md");
  fs.writeFileSync(skillPath, skillMd, "utf-8");
  files.push(skillPath);

  return { files, dir };
}

// ── Tool Scaffold ────────────────────────────────────────────────────────────

/**
 * Generates a tool skeleton with name, description, inputSchema, and
 * an async execute function.
 *
 * @param {string} name - Tool name (e.g. "database.query")
 * @param {string} outputDir - Directory to write files into
 * @returns {{ files: string[], dir: string }}
 */
function scaffoldTool(name, outputDir) {
  const sanitized = sanitizeName(name);
  const dir = path.resolve(outputDir, sanitized);
  const files = [];

  fs.mkdirSync(dir, { recursive: true });

  const toolCode = [
    `"use strict";`,
    ``,
    `/**`,
    ` * ${sanitized} tool.`,
    ` *`,
    ` * Generated by the dev-tooling scaffolder.`,
    ` */`,
    ``,
    `function create${toPascalCase(name.replace(/\./g, "_"))}Tool() {`,
    `  return {`,
    `    name: "${name}",`,
    `    description: "TODO: describe what this tool does and when to use it",`,
    `    inputSchema: {`,
    `      type: "object",`,
    `      required: ["input"],`,
    `      properties: {`,
    `        input: {`,
    `          type: "string",`,
    `          description: "The input parameter for this tool",`,
    `        },`,
    `      },`,
    `    },`,
    ``,
    `    /**`,
    `     * Execute the tool.`,
    `     * @param {object} args - The resolved input arguments`,
    `     * @param {object} context - Tool execution context (root, session, etc.)`,
    `     * @returns {Promise<object>}`,
    `     */`,
    `    async execute(args, context) {`,
    `      // TODO: validate args, perform the operation, return a result`,
    `      const { input } = args;`,
    ``,
    `      return {`,
    `        ok: true,`,
    `        input,`,
    `        message: "Tool executed successfully",`,
    `      };`,
    `    },`,
    `  };`,
    `}`,
    ``,
    `module.exports = { create${toPascalCase(name.replace(/\./g, "_"))}Tool };`,
    ``,
  ].join("\n") + "\n";

  const toolPath = path.join(dir, "index.js");
  fs.writeFileSync(toolPath, toolCode, "utf-8");
  files.push(toolPath);

  return { files, dir };
}

// ── Agent Scaffold ───────────────────────────────────────────────────────────

/**
 * Generates an agent definition skeleton.
 *
 * @param {string} name - Agent name (e.g. "code-reviewer")
 * @param {string} outputDir - Directory to write files into
 * @returns {{ files: string[], dir: string }}
 */
function scaffoldAgent(name, outputDir) {
  const sanitized = sanitizeName(name);
  const dir = path.resolve(outputDir, sanitized);
  const files = [];

  fs.mkdirSync(dir, { recursive: true });

  const agentCode = [
    `"use strict";`,
    ``,
    `/**`,
    ` * Agent definition: ${sanitized}`,
    ` *`,
    ` * Generated by the dev-tooling scaffolder.`,
    ` */`,
    ``,
    `const agent = {`,
    `  name: "${sanitized}",`,
    `  description: "TODO: describe this agent's purpose and capabilities",`,
    ``,
    `  /** Provider configuration */`,
    `  provider: {`,
    `    type: "anthropic",`,
    `    model: "claude-sonnet-4-20250514",`,
    `  },`,
    ``,
    `  /** System prompt / instructions */`,
    `  instructions: [`,
    `    "TODO: write the system prompt that defines this agent's behaviour.",`,
    `  ],`,
    ``,
    `  /** Tools this agent has access to */`,
    `  tools: [`,
    `    "file.read",`,
    `    "file.write",`,
    `    "file.edit",`,
    `    "shell",`,
    `    // TODO: add or remove tools as needed`,
    `  ],`,
    ``,
    `  /** Agent-specific settings */`,
    `  settings: {`,
    `    maxTurns: 20,`,
    `    temperature: 0.2,`,
    `    // TODO: tweak settings for this agent`,
    `  },`,
    ``,
    `  /** Sub-agents (if any) */`,
    `  agents: [],`,
    `};`,
    ``,
    `module.exports = agent;`,
    ``,
  ].join("\n") + "\n";

  const agentPath = path.join(dir, "index.js");
  fs.writeFileSync(agentPath, agentCode, "utf-8");
  files.push(agentPath);

  return { files, dir };
}

// ── Test Scaffold ────────────────────────────────────────────────────────────

/**
 * Generates a test skeleton with placeholder test cases.
 *
 * @param {string} name - Test name (e.g. "my-module")
 * @param {string} outputDir - Directory to write files into
 * @returns {{ files: string[], dir: string }}
 */
function scaffoldTest(name, outputDir) {
  const sanitized = sanitizeName(name);
  const dir = path.resolve(outputDir);
  const files = [];

  fs.mkdirSync(dir, { recursive: true });

  const testCode = [
    `/**`,
    ` * Tests for ${sanitized}.`,
    ` */`,
    `"use strict";`,
    ``,
    `const assert = require("node:assert/strict");`,
    `const test = require("node:test");`,
    ``,
    `// TODO: Adjust the require path to your module`,
    `// const { myFunction } = require("../src/${sanitized}");`,
    ``,
    `test("${sanitized}: basic functionality", () => {`,
    `  // Arrange`,
    `  const input = "hello";`,
    ``,
    `  // Act — replace with actual function call`,
    `  const result = typeof input === "string";`,
    ``,
    `  // Assert`,
    `  assert.equal(result, true);`,
    `});`,
    ``,
    `test("${sanitized}: handles edge case", () => {`,
    `  // TODO: test edge cases`,
    `  assert.equal(1 + 1, 2);`,
    `});`,
    ``,
    `test("${sanitized}: handles error conditions", () => {`,
    `  assert.throws(`,
    `    () => { throw new Error("test error"); },`,
    `    { message: /test error/ }`,
    `  );`,
    `});`,
    ``,
  ].join("\n") + "\n";

  const testPath = path.join(dir, `${sanitized}.test.js`);
  fs.writeFileSync(testPath, testCode, "utf-8");
  files.push(testPath);

  return { files, dir };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Sanitize a name to a safe kebab-case identifier.
 */
function sanitizeName(raw) {
  return String(raw)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-")
    || "untitled";
}

/**
 * Convert kebab-case to camelCase.
 */
function toCamelCase(str) {
  return str.replace(/[-_.]([a-z])/g, (_, c) => c.toUpperCase());
}

/**
 * Convert to PascalCase.
 */
function toPascalCase(str) {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

module.exports = {
  scaffoldPlugin,
  scaffoldSkill,
  scaffoldTool,
  scaffoldAgent,
  scaffoldTest,
};
