"use strict";

const { TemplateEngine } = require("../optimizer/template-engine");

/**
 * TemplateRegistry
 *
 * Manages a collection of named, categorised templates.  Provides registration,
 * generation (via the existing TemplateEngine), listing, and pre-generation
 * validation so callers can discover missing variables before rendering.
 *
 * Built-in templates cover common project files: package.json, tsconfig.json,
 * .env, docker-compose, Makefile, and CI pipelines (GitHub Actions / GitLab CI).
 */

// ── Template definition shape ────────────────────────────────────────────────
// Each registered template is an object:
// {
//   name:       string                                          // unique key
//   template:   string                                          // raw template text
//   category:   string                                          // grouping key
//   description: string                                         // human-readable
//   required:   string[]                                        // mandatory variables
// }

const BUILTIN_CATEGORY = "builtin";

// ── Built-in template content ────────────────────────────────────────────────

const PACKAGE_JSON_TPL = `{
  "name": "{{name}}",
  "version": "{{version}}",
  "description": "{{description}}",
  "main": "{{main}}",
  "scripts": {
    "start": "{{startScript}}",
    "test": "{{testScript}}",
    "build": "{{buildScript}}",
    "lint": "{{lintScript}}"
  },
  {{keywordsBlock}}
  "author": "{{author}}",
  "license": "{{license}}"{{dependenciesBlock}}{{devDependenciesBlock}}
}`;

const TSCONFIG_JSON_TPL = `{
  "compilerOptions": {
    "target": "{{target}}",
    "module": "{{module}}",
    "moduleResolution": "{{moduleResolution}}",
    "strict": {{strict}},
    "esModuleInterop": {{esModuleInterop}},
    "skipLibCheck": {{skipLibCheck}},
    "forceConsistentCasingInFileNames": true,
    "outDir": "{{outDir}}",
    "rootDir": "{{rootDir}}",
    "declaration": {{declaration}},
    "sourceMap": {{sourceMap}}{{jsxBlock}},
    "paths": {
      {{pathsBlock}}
    }
  },
  "include": [{{include}}],
  "exclude": [{{exclude}}]
}`;

const DOTENV_TPL = `# {{name}} environment configuration
# Generated by HaxAgent template engine

# ── Application ──────────────────────────────────────────────────────────────
NODE_ENV={{nodeEnv}}
PORT={{port}}
HOST={{host}}

# ── API Keys ─────────────────────────────────────────────────────────────────
{{#each apiKeys}}
{{key}}={{value}}
{{/each}}

# ── Database ─────────────────────────────────────────────────────────────────
{{#if dbHost}}
DB_HOST={{dbHost}}
{{/if}}
{{#if dbPort}}
DB_PORT={{dbPort}}
{{/if}}
{{#if dbName}}
DB_NAME={{dbName}}
{{/if}}
{{#if dbUser}}
DB_USER={{dbUser}}
{{/if}}

# ── Logging ──────────────────────────────────────────────────────────────────
LOG_LEVEL={{logLevel}}
LOG_FORMAT={{logFormat}}

# ── Feature Flags ────────────────────────────────────────────────────────────
{{#each featureFlags}}
{{name}}={{enabled}}
{{/each}}
`;

const DOCKER_COMPOSE_TPL = `version: "{{composeVersion}}"

services:
  {{name}}:
    build:
      context: {{buildContext}}
      dockerfile: {{dockerfile}}
    container_name: {{containerName}}
    ports:
      - "{{hostPort}}:{{containerPort}}"
    environment:
      {{#each envVars}}
      - {{key}}={{value}}
      {{/each}}
    volumes:
      {{#each volumes}}
      - {{source}}:{{target}}
      {{/each}}
    restart: {{restartPolicy}}
    {{#if networks}}
    networks:
      {{#each networks}}
      - {{name}}
      {{/each}}
    {{/if}}
    {{#if dependsOn}}
    depends_on:
      {{#each dependsOn}}
      - {{name}}
      {{/each}}
    {{/if}}
`;

const MAKEFILE_TPL = `# {{name}} Makefile
# Generated by HaxAgent template engine

.DEFAULT_GOAL := help
SHELL := /bin/bash
.PHONY: help

# ── Variables ────────────────────────────────────────────────────────────────
NODE_BIN := ./node_modules/.bin
SRC_DIR  := {{srcDir}}
TEST_DIR := {{testDir}}

# ── Development ──────────────────────────────────────────────────────────────

## install          Install all dependencies
install:
\t{{installCmd}}

## build            Build the project
build:
\t{{buildCmd}}

## dev              Start development server with hot-reload
dev:
\t{{devCmd}}

## start            Start production server
start:
\t{{startCmd}}

# ── Testing ──────────────────────────────────────────────────────────────────

## test             Run all tests
test:
\t{{testCmd}}

## test-watch       Run tests in watch mode
test-watch:
\t{{testWatchCmd}}

## coverage         Generate test coverage report
coverage:
\t{{coverageCmd}}

# ── Code Quality ─────────────────────────────────────────────────────────────

## lint             Run linter
lint:
\t{{lintCmd}}

## format           Format source code
format:
\t{{formatCmd}}

## typecheck        Run type checker
typecheck:
\t{{typecheckCmd}}

# ── Utilities ────────────────────────────────────────────────────────────────

## clean            Remove build artifacts and dependencies
clean:
\t{{cleanCmd}}

## docker-build     Build Docker image
docker-build:
\tdocker build -t {{dockerImage}} .

## docker-run       Run Docker container
docker-run:
\tdocker run -p {{hostPort}}:{{containerPort}} {{dockerImage}}

# ── Help ─────────────────────────────────────────────────────────────────────

help: ## Show this help
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \\
\t\tawk 'BEGIN {FS = ":.*?## "}; {printf "\\033[36m%-20s\\033[0m %s\\n", $$1, $$2}'
`;

const GITHUB_ACTIONS_TPL = `name: {{workflowName}}

on:
  push:
    branches: [{{pushBranches}}]
  pull_request:
    branches: [{{prBranches}}]

jobs:
  {{jobName}}:
    runs-on: {{runsOn}}
    {{#if strategyMatrix}}
    strategy:
      matrix:
        {{#each strategyMatrix}}
        {{key}}: [{{value}}]
        {{/each}}
    {{/if}}
    steps:
      - uses: actions/checkout@v4

      {{#if setupNode}}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: {{nodeVersion}}
          cache: "{{nodePackageManager}}"
      {{/if}}

      {{#if setupPython}}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{pythonVersion}}"
      {{/if}}

      {{#each steps}}
      - name: {{name}}
        run: {{run}}
        {{#if env}}
        env:
          {{#each env}}
          {{key}}: {{value}}
          {{/each}}
        {{/if}}
      {{/each}}
`;

const GITLAB_CI_TPL = `stages:
  {{#each stages}}
  - {{name}}
  {{/each}}

variables:
  {{#each variables}}
  {{key}}: "{{value}}"
  {{/each}}

{{#each jobs}}
{{name}}:
  stage: {{stage}}
  image: {{image}}
  script:
    {{#each script}}
    - {{line}}
    {{/each}}
  {{#if artifacts}}
  artifacts:
    paths:
      {{#each artifacts}}
      - {{path}}
      {{/each}}
  {{/if}}
  {{#if only}}
  only:
    {{#each only}}
    - {{ref}}
    {{/each}}
  {{/if}}
  {{#if except}}
  except:
    {{#each except}}
    - {{ref}}
    {{/each}}
  {{/if}}

{{/each}}
`;

// ── TemplateRegistry ─────────────────────────────────────────────────────────

class TemplateRegistry {
  /**
   * @param {object} [options]
   * @param {TemplateEngine} [options.engine] — inject a custom TemplateEngine
   */
  constructor(options = {}) {
    /** @type {TemplateEngine} */
    this._engine = options.engine || new TemplateEngine();

    /** @type {Map<string, object>} name -> template definition */
    this._templates = new Map();

    this._registerBuiltins();
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /**
   * Register a template.
   *
   * @param {string} name         — unique template name
   * @param {object} templateDef  — { template, category?, description?, required? }
   * @param {string} [templateDef.template]     — template string with {{var}} syntax
   * @param {string} [templateDef.category="general"] — grouping category
   * @param {string} [templateDef.description=""]     — human-readable description
   * @param {string[]} [templateDef.required=[]]      — mandatory variable names
   * @returns {this}
   */
  register(name, templateDef) {
    if (!name || typeof name !== "string") {
      throw new TypeError("TemplateRegistry.register: name must be a non-empty string");
    }
    if (!templateDef || typeof templateDef !== "object") {
      throw new TypeError("TemplateRegistry.register: templateDef must be an object");
    }
    if (typeof templateDef.template !== "string") {
      throw new TypeError("TemplateRegistry.register: templateDef.template must be a string");
    }

    const def = {
      name,
      template: templateDef.template,
      category: templateDef.category || "general",
      description: templateDef.description || "",
      required: Array.isArray(templateDef.required) ? templateDef.required : [],
    };

    this._templates.set(name, def);
    return this;
  }

  /**
   * Generate output from a named template merged with the supplied variables.
   *
   * @param {string} name       — registered template name
   * @param {object} [variables={}] — key-value map for template substitution
   * @returns {string} Rendered output.
   */
  generate(name, variables = {}) {
    const def = this._templates.get(name);
    if (!def) {
      throw new Error(`TemplateRegistry.generate: unknown template "${name}"`);
    }
    return this._engine.compile(def.template, variables);
  }

  /**
   * List registered templates, optionally filtered by category.
   *
   * @param {string} [category] — if provided, only return templates in this category
   * @returns {Array<{ name: string, category: string, description: string, required: string[] }>}
   */
  listTemplates(category) {
    const result = [];
    for (const [, def] of this._templates) {
      if (category === undefined || def.category === category) {
        result.push({
          name: def.name,
          category: def.category,
          description: def.description,
          required: def.required,
        });
      }
    }
    return result.sort((a, b) => a.name.localeCompare(b.name));
  }

  /**
   * Validate that the supplied variables satisfy the template's required
   * fields.  Also runs the template engine's structural validation.
   *
   * @param {string} name       — registered template name
   * @param {object} [variables={}] — variables to check
   * @returns {{ valid: boolean, errors: string[], warnings: string[] }}
   */
  validate(name, variables = {}) {
    const def = this._templates.get(name);
    if (!def) {
      return { valid: false, errors: [`Unknown template: "${name}"`], warnings: [] };
    }

    const errors = [];
    const warnings = [];

    // Check required variables.
    for (const req of def.required) {
      const val = this._engine._resolve
        ? this._engine._resolve(req, variables)
        : variables[req];

      if (val === null || val === undefined || val === "") {
        errors.push(`Missing required variable: "${req}"`);
      }
    }

    // Structural validation of the template itself.
    const struct = this._engine.validateTemplate(def.template);
    if (!struct.valid) {
      errors.push(...struct.errors);
    }

    // Extract all referenced variables and warn about ones that are missing.
    const referenced = this._engine.extractVariables(def.template);
    for (const ref of referenced) {
      // Skip block keywords like "isLast", "item" which are injected by the engine.
      if (ref === "isLast" || ref === "item") continue;

      const val = this._engine._resolve
        ? this._engine._resolve(ref, variables)
        : variables[ref];

      if (val === null || val === undefined || val === "") {
        warnings.push(`Variable "${ref}" is used in the template but not provided`);
      }
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
    };
  }

  /**
   * Remove a template from the registry.
   *
   * @param {string} name
   * @returns {boolean} true if removed, false if not found
   */
  unregister(name) {
    return this._templates.delete(name);
  }

  /**
   * Return the number of registered templates.
   *
   * @returns {number}
   */
  get size() {
    return this._templates.size;
  }

  /**
   * Return the list of all categories.
   *
   * @returns {string[]}
   */
  getCategories() {
    const cats = new Set();
    for (const [, def] of this._templates) {
      cats.add(def.category);
    }
    return [...cats].sort();
  }

  // ---------------------------------------------------------------------------
  // Private: built-in registration
  // ---------------------------------------------------------------------------

  /** @private */
  _registerBuiltins() {
    const builtins = [
      {
        name: "package.json",
        template: PACKAGE_JSON_TPL,
        category: BUILTIN_CATEGORY,
        description: "Node.js package.json manifest",
        required: ["name", "version"],
      },
      {
        name: "tsconfig.json",
        template: TSCONFIG_JSON_TPL,
        category: BUILTIN_CATEGORY,
        description: "TypeScript compiler configuration",
        required: [],
      },
      {
        name: ".env",
        template: DOTENV_TPL,
        category: BUILTIN_CATEGORY,
        description: "Environment variable file",
        required: [],
      },
      {
        name: "docker-compose",
        template: DOCKER_COMPOSE_TPL,
        category: BUILTIN_CATEGORY,
        description: "Docker Compose service definition",
        required: ["name"],
      },
      {
        name: "Makefile",
        template: MAKEFILE_TPL,
        category: BUILTIN_CATEGORY,
        description: "GNU Make build automation",
        required: ["name"],
      },
      {
        name: "github-actions",
        template: GITHUB_ACTIONS_TPL,
        category: BUILTIN_CATEGORY,
        description: "GitHub Actions CI workflow",
        required: ["workflowName", "jobName"],
      },
      {
        name: "gitlab-ci",
        template: GITLAB_CI_TPL,
        category: BUILTIN_CATEGORY,
        description: "GitLab CI/CD pipeline configuration",
        required: ["name"],
      },
    ];

    for (const b of builtins) {
      this._templates.set(b.name, b);
    }
  }
}

// ── Exports ──────────────────────────────────────────────────────────────────

module.exports = {
  TemplateRegistry,
  // Also export the raw template strings so callers can inspect / customise:
  PACKAGE_JSON_TPL,
  TSCONFIG_JSON_TPL,
  DOTENV_TPL,
  DOCKER_COMPOSE_TPL,
  MAKEFILE_TPL,
  GITHUB_ACTIONS_TPL,
  GITLAB_CI_TPL,
};
