'use strict';

const ANSI = {
  reset: '\x1B[0m',
  bold: '\x1B[1m',
  dim: '\x1B[2m',
  italic: '\x1B[3m',
  underline: '\x1B[4m',
  strikethrough: '\x1B[9m',
  inverse: '\x1B[7m',
  hidden: '\x1B[8m',
  black: '\x1B[30m',
  red: '\x1B[31m',
  green: '\x1B[32m',
  yellow: '\x1B[33m',
  blue: '\x1B[34m',
  magenta: '\x1B[35m',
  cyan: '\x1B[36m',
  white: '\x1B[37m',
  brightRed: '\x1B[91m',
  brightGreen: '\x1B[92m',
  brightYellow: '\x1B[93m',
  brightBlue: '\x1B[94m',
  brightMagenta: '\x1B[95m',
  brightCyan: '\x1B[96m',
  brightWhite: '\x1B[97m',
  bgBlack: '\x1B[40m',
  bgRed: '\x1B[41m',
  bgGreen: '\x1B[42m',
  bgYellow: '\x1B[43m',
  bgBlue: '\x1B[44m',
  bgMagenta: '\x1B[45m',
  bgCyan: '\x1B[46m',
  bgWhite: '\x1B[47m',
  bgBrightBlack: '\x1B[100m',
  bgBrightBlue: '\x1B[104m',
  bgBrightMagenta: '\x1B[105m',
  bgBrightCyan: '\x1B[106m',
  clearScreen: '\x1B[2J',
  clearLine: '\x1B[2K',
  clearLineRight: '\x1B[K',
  clearLineLeft: '\x1B[1K',
  cursorHome: '\x1B[H',
  cursorUp: '\x1B[A',
  cursorDown: '\x1B[B',
  cursorRight: '\x1B[C',
  cursorLeft: '\x1B[D',
  cursorSave: '\x1B[s',
  cursorRestore: '\x1B[u',
  cursorShow: '\x1B[?25h',
  cursorHide: '\x1B[?25l',
  cursorTo: (row, col) => `\x1B[${row};${col}H`,
  scrollUp: (n) => `\x1B[${n}S`,
  scrollDown: (n) => `\x1B[${n}T`,
  setScrollRegion: (top, bottom) => `\x1B[${top};${bottom}r`,
  altScreenOn: '\x1B[?1049h',
  altScreenOff: '\x1B[?1049l',
  bracketedPasteOn: '\x1B[?2004h',
  bracketedPasteOff: '\x1B[?2004l',
  focusOn: '\x1B[?1004h',
  focusOff: '\x1B[?1004l',
};

const THEME = {
  userIndicator: ANSI.brightCyan,
  assistantIndicator: ANSI.brightMagenta,
  toolIndicator: ANSI.brightYellow,
  toolSuccess: ANSI.brightGreen,
  toolError: ANSI.brightRed,
  thinkingIndicator: ANSI.dim + ANSI.italic,
  codeBlock: ANSI.bgBrightBlack,
  codeText: ANSI.brightCyan,
  heading: ANSI.bold + ANSI.brightCyan,
  bold: ANSI.bold + ANSI.brightWhite,
  italic: ANSI.italic,
  link: ANSI.underline + ANSI.brightBlue,
  list: ANSI.brightYellow,
  hr: ANSI.dim,
  dimText: ANSI.dim,
  dim: ANSI.dim,
  statusLine: ANSI.bgBrightBlack + ANSI.brightWhite,
  promptPrefix: ANSI.brightGreen,
  promptCaret: ANSI.brightWhite,
  error: ANSI.brightRed,
  warning: ANSI.brightYellow,
  success: ANSI.brightGreen,
  info: ANSI.brightBlue,
  muted: ANSI.dim,
  accent: ANSI.brightMagenta,
  diffAdd: ANSI.brightGreen,
  diffRemove: ANSI.brightRed,
  diffContext: ANSI.dim,
  diffHeader: ANSI.brightCyan,
  spinner: ANSI.brightCyan,
  cost: ANSI.brightYellow,
  token: ANSI.dim,
  border: ANSI.dim,
  badge: ANSI.bgBrightBlack + ANSI.brightWhite,
  skillIndicator: ANSI.brightGreen + ANSI.bold,
  shellIndicator: ANSI.brightYellow,
};

function stripAnsi(text) {
  return text.replace(/\x1B\[[0-?]*[ -/]*[@-~]/g, '');
}

export { ANSI, THEME, stripAnsi };
